### ISSUE TITLE
Can this feedstock add `osx-arm64` to it's build pipelines?

### ISSUE THREAD

**Issue by darynwhite** [conda-forge/lttbc-feedstock#4]
### Comment:

Based on what I have read here: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

I'm wondering if this feedstock can be build for `macos-arm64`?

We may need the help of @conda-forge/help-osx-arm64

**Comment by erykoff** [comment]
Fixed with #5

**Comment by darynwhite** [comment]
Thank you @erykoff!
